local M = {}

function M.setup(ctx)
  local _ENV = ctx
  bind(main_mod .. " + P", exec(launcher_command))
  bind(main_mod .. " + SHIFT + P", exec(run_menu))
  bind(hyper .. " + SHIFT + N", exec(shell_ui_command .. " control-center"))
  bind(hyper .. " + CTRL + N", exec(shell_ui_command .. " settings"))
  bind(main_mod .. " + SHIFT + Return", exec(terminal))
  bind(main_mod .. " + Q", exec("hyprctl reload"))
  bind(main_mod .. " + SHIFT + C", hl.dsp.window.close())
  bind(main_mod .. " + SHIFT + Q", hl.dsp.exit())
  bind(main_mod .. " + E", exec("emacsclient --eval '(emacs-everywhere)'"))
  bind(main_mod .. " + V", exec("wl-paste | xdotool type --file -"))
  bind(main_mod .. " + Tab", hyprwinview({
    action = "show",
    start_in_filter_mode = true,
    default_action = "bring",
  }), overview_bind_opts)
  bind(main_mod .. " + SHIFT + Tab", hyprwinview({
    action = "show",
    include_current_workspace = false,
    start_in_filter_mode = true,
    default_action = "bring",
  }), overview_bind_opts)
  bind(main_mod .. " + SHIFT + slash", hyprwinview({ action = "toggle-filter" }), overview_bind_opts)
  bind("ALT + Tab", hyprspace("toggle"), overview_bind_opts)
  bind("ALT + SHIFT + Tab", hyprexpo("open"), overview_bind_opts)
  bind(main_mod .. " + G", hyprwinview({
    action = "show",
    start_in_filter_mode = true,
    default_action = "select",
  }), overview_bind_opts)
  bind(main_mod .. " + B", hyprwinview({
    action = "show",
    start_in_filter_mode = true,
    default_action = "bring",
  }), overview_bind_opts)
  bind(main_mod .. " + SHIFT + B", hyprwinview({
    action = "show",
    start_in_filter_mode = true,
    default_action = "bring-replace",
  }), overview_bind_opts)

  bind(main_mod .. " + W", function()
    focus_direction("up")
  end)
  bind(main_mod .. " + S", function()
    focus_direction("down")
  end)
  bind(main_mod .. " + A", function()
    focus_direction("left")
  end)
  bind(main_mod .. " + D", function()
    focus_direction("right")
  end)

  bind(main_mod .. " + SHIFT + W", function()
    swap_direction("up")
  end)
  bind(main_mod .. " + SHIFT + S", function()
    swap_direction("down")
  end)
  bind(main_mod .. " + SHIFT + A", function()
    swap_direction("left")
  end)
  bind(main_mod .. " + SHIFT + D", function()
    swap_direction("right")
  end)

  bind(main_mod .. " + CTRL + W", function()
    move_window_to_monitor("u", false)
  end)
  bind(main_mod .. " + CTRL + S", function()
    move_window_to_monitor("d", false)
  end)
  bind(main_mod .. " + CTRL + A", function()
    move_window_to_monitor("l", false)
  end)
  bind(main_mod .. " + CTRL + D", function()
    move_window_to_monitor("r", false)
  end)
  bind(main_mod .. " + CTRL + SHIFT + W", function()
    move_window_to_empty_workspace_on_monitor("u")
  end)
  bind(main_mod .. " + CTRL + SHIFT + S", function()
    move_window_to_empty_workspace_on_monitor("d")
  end)
  bind(main_mod .. " + CTRL + SHIFT + A", function()
    move_window_to_empty_workspace_on_monitor("l")
  end)
  bind(main_mod .. " + CTRL + SHIFT + D", function()
    move_window_to_empty_workspace_on_monitor("r")
  end)

  hl.define_submap("swap-workspace", function()
    for i = 1, 9 do
      local workspace_id = i
      bind(tostring(i), function()
        swap_current_workspace_with(workspace_id)
        dispatch(hl.dsp.submap("reset"))
      end)
    end

    bind("Escape", hl.dsp.submap("reset"))
    bind("catchall", hl.dsp.submap("reset"))
  end)

  hl.define_submap("window-picker", function()
    for i = 1, 9 do
      local index = i
      bind(tostring(i), function()
        activate_window_picker_candidate(index)
      end)
    end

    bind("Escape", hl.dsp.submap("reset"))
    bind("catchall", hl.dsp.submap("reset"))
  end)

  bind(mod_alt .. " + SHIFT + W", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
  bind(mod_alt .. " + SHIFT + S", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
  bind(mod_alt .. " + SHIFT + A", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
  bind(mod_alt .. " + SHIFT + D", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })

  bind(hyper .. " + W", hl.dsp.focus({ monitor = "u" }))
  bind(hyper .. " + S", hl.dsp.focus({ monitor = "d" }))
  bind(hyper .. " + A", hl.dsp.focus({ monitor = "l" }))
  bind(hyper .. " + D", hl.dsp.focus({ monitor = "r" }))
  bind(hyper .. " + SHIFT + W", function()
    move_window_to_monitor("u", true)
  end)
  bind(hyper .. " + SHIFT + S", function()
    move_window_to_monitor("d", true)
  end)
  bind(hyper .. " + SHIFT + A", function()
    move_window_to_monitor("l", true)
  end)
  bind(hyper .. " + SHIFT + D", function()
    move_window_to_monitor("r", true)
  end)

  bind(main_mod .. " + Space", cycle_layout_or_restore_tabbed_group)
  bind(main_mod .. " + SHIFT + Space", force_columns_layout)
  bind(main_mod .. " + CTRL + Space", gather_workspace_into_tabbed_group)
  bind(main_mod .. " + bracketright", monocle_next)
  bind(main_mod .. " + bracketleft", monocle_prev)
  bind(main_mod .. " + T", hl.dsp.window.float({ action = "disable" }))
  bind(main_mod .. " + O", toggle_pinned_active_window)
  bind(main_mod .. " + M", minimize_active_window)
  bind(main_mod .. " + SHIFT + M", restore_last_minimized)
  bind(main_mod .. " + CTRL + SHIFT + M", function()
    enter_window_picker("minimized")
  end)
  bind(main_mod .. " + SHIFT + equal", schedule_nstack_count_update)
  bind(main_mod .. " + CTRL + M", hl.dsp.window.toggle_swallow())
  bind(main_mod .. " + SHIFT + E", function()
    move_to_next_empty_workspace(true)
  end)
  bind(main_mod .. " + CTRL + E", function()
    move_to_next_empty_workspace(false)
  end)
  bind(main_mod .. " + apostrophe", focus_next_class)
  bind(mod_alt .. " + W", show_active_window_info)

  bind(main_mod .. " + X", exec("rofi_command.sh"))
  bind(main_mod .. " + SHIFT + X", hl.dsp.workspace.toggle_special("NSP"))
  bind(mod_alt .. " + C", function()
    toggle_scratchpad("codex")
  end)
  bind(mod_alt .. " + E", function()
    toggle_scratchpad("element")
  end)
  bind(mod_alt .. " + H", function()
    toggle_scratchpad("htop")
  end)
  bind(mod_alt .. " + K", function()
    toggle_scratchpad("slack")
  end)
  bind(mod_alt .. " + M", function()
    toggle_scratchpad("messages")
  end)
  bind(mod_alt .. " + S", function()
    toggle_scratchpad("spotify")
  end)
  bind(mod_alt .. " + T", function()
    toggle_scratchpad("transmission")
  end)
  bind(mod_alt .. " + V", function()
    toggle_scratchpad("volume")
  end)
  bind(mod_alt .. " + grave", function()
    toggle_scratchpad("dropdown")
  end)
  bind(mod_alt .. " + Space", minimize_other_classes)
  bind(mod_alt .. " + SHIFT + Space", restore_focused_class)
  bind(mod_alt .. " + Return", restore_all_minimized)

  for i = 1, 9 do
    local workspace = tostring(i)
    bind(main_mod .. " + " .. workspace, hl.dsp.focus({ workspace = workspace, on_current_monitor = true }))
    bind(main_mod .. " + SHIFT + " .. workspace, hl.dsp.window.move({ workspace = workspace, follow = false }))
    bind(main_mod .. " + CTRL + " .. workspace, function()
      dispatch(hl.dsp.window.move({ workspace = workspace, follow = false }))
      dispatch(hl.dsp.focus({ workspace = workspace, on_current_monitor = true }))
    end)
  end

  bind(main_mod .. " + backslash", workspacehistory("cycle", 1))
  bind(main_mod .. " + slash", workspacehistory("cycle", -1))
  bind(main_mod .. " + Escape", workspacehistory("cancel"))
  bind(main_mod .. " + Z", hl.dsp.focus({ monitor = "+1" }))
  bind(main_mod .. " + SHIFT + Z", hl.dsp.window.move({ monitor = "+1" }))
  bind(main_mod .. " + mouse_down", function()
    cycle_workspace(1)
  end)
  bind(main_mod .. " + mouse_up", function()
    cycle_workspace(-1)
  end)
  bind(hyper .. " + E", focus_next_empty_workspace)
  bind(hyper .. " + 5", enter_workspace_swap_mode)
  bind(hyper .. " + G", gather_focused_class)

  bind(main_mod .. " + I", exec("set_volume --unmute --change-volume +5"), { repeating = true })
  bind(main_mod .. " + K", exec("set_volume --unmute --change-volume -5"), { repeating = true })
  bind(main_mod .. " + U", exec("set_volume --toggle-mute"))
  bind(main_mod .. " + semicolon", exec("playerctl play-pause"))
  bind(main_mod .. " + L", exec("playerctl next"))
  bind(main_mod .. " + J", exec("playerctl previous"))

  bind("XF86AudioPlay", exec("playerctl play-pause"))
  bind("XF86AudioPause", exec("playerctl play-pause"))
  bind("XF86AudioNext", exec("playerctl next"))
  bind("XF86AudioPrev", exec("playerctl previous"))
  bind("XF86AudioRaiseVolume", exec("set_volume --unmute --change-volume +5"), { repeating = true })
  bind("XF86AudioLowerVolume", exec("set_volume --unmute --change-volume -5"), { repeating = true })
  bind("XF86AudioMute", exec("set_volume --toggle-mute"))
  bind("XF86MonBrightnessUp", exec("brightness.sh up"), { repeating = true })
  bind("XF86MonBrightnessDown", exec("brightness.sh down"), { repeating = true })

  bind(hyper .. " + V", exec([[cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy]]))
  bind(hyper .. " + P", exec("rofi-pass"))
  bind("Print", exec("flameshot gui"))
  bind(hyper .. " + H", exec("flameshot gui"))
  bind(hyper .. " + C", exec("rofi_tmcodex.sh"))
  bind(hyper .. " + SHIFT + C", exec("rofi_tmcodex.sh resume"))
  bind(hyper .. " + SHIFT + L", exec("hyprlock"))
  bind(hyper .. " + L", exec("hypr_rofi_layout"))
  bind(hyper .. " + K", exec("rofi_kill_process.sh"))
  bind(hyper .. " + SHIFT + K", exec("rofi_kill_all.sh"))
  bind(hyper .. " + R", exec("rofi-systemd"))
  bind(hyper .. " + slash", function()
    hl.exec_cmd("toggle_taffybar")
    refresh_monitor_reserved_cache(0.25)
    refresh_active_scratchpad_geometries_later(600)
  end)
  bind(hyper .. " + I", exec("rofi_select_input.hs"))
  bind(hyper .. " + backslash", exec("/home/imalison/dotfiles/dotfiles/lib/functions/mpg341cx_input toggle"))
  bind(hyper .. " + SHIFT + backslash", workspacehistory("debug"))
  bind(hyper .. " + O", exec("/home/imalison/dotfiles/dotfiles/lib/functions/rofi_paswitch"))
  bind(hyper .. " + comma", exec("rofi_wallpaper.sh"))
  bind(hyper .. " + SHIFT + comma", exec("/home/imalison/dotfiles/dotfiles/lib/bin/neowall-wallpaper toggle"))
  bind(hyper .. " + Y", exec("rofi_agentic_skill"))
  bind(main_mod .. " + R", exec("hyprctl reload"))

  bind(main_mod .. " + mouse:272", float_and_drag_active_window)
  bind(main_mod .. " + mouse:273", float_and_resize_active_window)
end

return M
