# -*- mode: sh -*-
setxkbmap -layout "$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $2}')" -option ctrl:nocaps
xrdb -merge "$HOME/.Xresources"

# Disable screensaver
setterm -blank 0 -powersave off -powerdown 0
xset s off

# Increase the repeat rate
xset q rate 200 30
