#!/bin/bash -*- mode: sh; -*-
function command_exists {
    hash "$1" 2>/dev/null 1>/dev/null
}

function run_if_exists {
	command_exists "$1" && $@
}

setxkbmap -layout "$(setxkbmap -print | awk -F + '/xkb_symbols/ {print $2}')" -option ctrl:nocaps
xrdb -merge .Xresources

run_if_exists stalonetray &
run_if_exists xscreensaver -no-splash &
run_if_exists nm-applet --sm-disable &
run_if_exists feh --bg-scale /usr/share/backgrounds/gnome/Blinds.jpg &
run_if_exists copyq &
run_if_exists copyq hide
