general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = /home/imalison/dotfiles/dotfiles/lib/bin/hypr-screensaver start
    on-resume = /home/imalison/dotfiles/dotfiles/lib/bin/hypr-screensaver stop
}

listener {
    timeout = 900
    on-timeout = /home/imalison/dotfiles/dotfiles/lib/bin/hypr-screensaver stop && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && /home/imalison/dotfiles/dotfiles/lib/bin/hypr-screensaver stop
}
