background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    outer_color = rgb(edb443)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    rounding = 12
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%a %b %-d  %I:%M %p')"
    color = rgb(cdd6f4)
    font_size = 40
    font_family = Noto Sans
    position = 0, 80
    halign = center
    valign = center
}
