;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        isearch-backward-regexp
        isearch-printing-char
        kill-region
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-delete-char
        python-indent-electric-colon
        smex
        ))
