;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dired-do-rename
	git-rebase-squash
	git-rebase-undo
	isearch-forward-regexp
	isearch-other-control-char
	isearch-printing-char
	keyboard-quit
	kill-region
	python-indent-electric-colon
	sgml-slash
	skeleton-pair-insert-maybe
	universal-argument-minus
	))

(setq mc/cmds-to-run-once
      '(
	delete-horizontal-space
	isearch-delete-char
	smex
	))
