;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dired-do-rename
        forward-sexp
        git-rebase-squash
        git-rebase-undo
        isearch-forward-regexp
        isearch-other-control-char
        isearch-printing-char
        keyboard-quit
        kill-region
        python-indent-electric-colon
        sgml-slash
        skeleton-pair-insert-maybe
        tern-ac-dot-complete
        universal-argument-minus
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        delete-horizontal-space
        dired-toggle-read-only
        isearch-delete-char
        smex
        ))
