;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        backward-sexp
        beginning-of-visual-line
        delete-horizontal-space
        dired-do-rename
        end-of-visual-line
        eval-last-sexp
        forward-sexp
        git-rebase-squash
        git-rebase-undo
        go-mode-insert-and-indent
        helm-show-kill-ring
        imalison:avy
        imalison:multi-line
        indent-for-tab-command
        isearch-forward-regexp
        isearch-other-control-char
        isearch-printing-char
        keyboard-quit
        kill-region
        kill-visual-line
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        phi-search
        phi-search-backward
        python-indent-electric-colon
        sgml-slash
        skeleton-pair-insert-maybe
        sp-backward-sexp
        sp-forward-sexp
        sp-splice-sexp-killing-backward
        string-inflection-toggle
        tern-ac-dot-complete
        transpose-sexps
        transpose-words
        undo-redo
        universal-argument-minus
        wdired-finish-edit
        yaml-electric-backspace
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        dired-toggle-read-only
        helm-M-x
        ido-write-file
        isearch-delete-char
        smex
        ))
