;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        dired-do-rename
        eval-last-sexp
        forward-sexp
        git-rebase-squash
        git-rebase-undo
        helm-show-kill-ring
        indent-for-tab-command
        isearch-forward-regexp
        isearch-other-control-char
        isearch-printing-char
        keyboard-quit
        kill-region
        org-delete-char
        org-self-insert-command
        phi-search
        python-indent-electric-colon
        sgml-slash
        skeleton-pair-insert-maybe
        tern-ac-dot-complete
        undo-redo
        universal-argument-minus
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        delete-horizontal-space
        dired-toggle-read-only
        isearch-delete-char
        smex
        ))
