[general]
import = ["/home/imalison/.config/alacritty/themes/themes/dracula.toml"]

[font]
size = 8

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"

[window.padding]
x = 10
y = 10
