#!/usr/bin/env sh

function get_cols {
	FS="${FS:- }"
	gawk -v "cols=$*" -v "FS=$FS" '
		BEGIN {
			column_count = split(cols, column_numbers, " ")
		}
		{
			for (i = 1; i <= column_count; i++) {
				if (column_numbers[i] < 0)
					printf "%s", $(NF + 1 + column_numbers[i])
				else
					printf "%s", $column_numbers[i]
				printf "%s", OFS
			}
			printf "%s", ORS
		}'
}

get_cols "$@"
