#!/usr/bin/env zsh

function github_clone {
  emulate -L zsh

  if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    clone-project --help
  elif [[ "${1:-}" == "--user" || "${1:-}" == "--internal-owners" || "${1:-}" == "--internal-owner-repositories" ]]; then
    clone-project "$@"
  elif [[ "${1:-}" == "--internal-repositories" ]]; then
    clone-project "$@"
  else
    clone-project --search "$@"
  fi
}

github_clone "$@"
