#!/usr/bin/env sh

function load_default_map {
	XKBDIR="$HOME/.xkb"
	XKBMAPFILE="$XKBDIR/keymap/default"

	echo "loading keymap from $XKBMAPFILE"

	xkbcomp -I"$XKBDIR" "$XKBMAPFILE" "${DISPLAY%%.*}"
}

load_default_map
