#!/usr/bin/env bash

# Taken from https://raw.githubusercontent.com/mpapis/home_dotfiles/master/bin/mypa

function list_sinks()
{
  local default_sink
  default_sink="$(pactl get-default-sink 2>/dev/null || true)"

  pactl list short sinks |
    while IFS=$'\t' read -r id name _; do
      if [ "$name" = "$default_sink" ]; then
        printf '  * index: %s\n' "$id"
      else
        printf '    index: %s\n' "$id"
      fi
      printf '\tname: <%s>\n' "$name"
    done
}

function switch_sink_default()
{
  echo switching default
  pactl set-default-sink "$1" || echo failed
}

function switch_sink_applications()
{
  echo switching applications
  pactl list short sink-inputs |
    awk '{print $1}' |
    xargs -r -I{} pactl move-sink-input {} "$1" ||
      echo failed
}

function switch_sink_kmix_master()
{
  qdbus org.kde.kmix >/dev/null 2>&1 || return 0 # kmix not found

  typeset name mixer
  # get the device name in pulseaudio
  name="$(
    pactl list short sinks | awk -v search="$1" '$1 == search {print $2}'
  )"
  # format device name to a name in kmix
  name="${name#<}"
  name="${name%>}"
  name="${name//[.-]/_}"
  # grab full path in kmix dbus
  mixer="$( qdbus org.kde.kmix | \grep "/${name}$" )"
  mixer="${mixer#/Mixers/}"
  mixer="${mixer%/*}"
  # get the kmix ids
  name="$( qdbus org.kde.kmix "/Mixers/${mixer}/${name}" org.kde.KMix.Control.id)"
  mixer="$(qdbus org.kde.kmix "/Mixers/${mixer}"         org.kde.KMix.Mixer.id  )"
  echo "set master channel in kmix"
  qdbus org.kde.kmix /Mixers org.kde.KMix.MixSet.setCurrentMaster "$mixer" "$name" >/dev/null || echo failed
}

function switch_sink()
{
  switch_sink_default      "$@"
  switch_sink_applications "$@"
  switch_sink_kmix_master  "$@"
}

# Use a zenity gui to switch audio outputs
function switch_gui()
{
# get current output id, all output ids and the sink names
   current_name="$(pactl get-default-sink)"
   current_id="$(pactl list short sinks | awk -v name="$current_name" '$2 == name {print $1}')"
   ids=( $(pactl list short sinks | awk '{print $1}' | tr '\n' ' ') )
   names=( $(pactl list short sinks | awk '{print $2}' | tr '\n' ' ') )

   zen_pars="--list --radiolist --column '' --column 'ID' --column 'Sink_name'"

# construct the zenity command
   for i in "${!ids[@]}"
   do
      if [ ${ids[$i]} = $current_id ]; then
         zen_pars="$zen_pars TRUE"
      else
         zen_pars="$zen_pars FALSE"
      fi
      zen_pars="$zen_pars ${ids[$i]} ${names[$i]}"
   done

# change the audio sink with the switch_sink function
   new_sink_id=$(zenity $zen_pars || echo "")
   if [ -n $new_sink_id ]; then
      switch_sink $new_sink_id
   fi
}

function help_me()
{
  echo "Usage: $0 [gui|list|<sink name to switch to>]"
}

function pahelper {
  case "${1:-}" in
	(""|list) list_sinks       ;;
	([0-9]*)  switch_sink "$@" ;;
	(gui)     switch_gui       ;;
	(*)       help_me          ;;
  esac
}

pahelper "$@"
