#!/usr/bin/env sh

function pashowvolume {
	if paismuted; then
		rumno notify -m
	else
		actual=$(pavolume)
		max=100
		show=$(( actual < max ? actual : max ))
		rumno notify -v "$show"
	fi
}

pashowvolume

