#!/usr/bin/env sh

function pashowvolume {
	timeout="${RUMNO_TIMEOUT:-2.5}"
	if paismuted; then
		rumno -t "$timeout" -m true
	else
		actual=$(pavolume)
		max=100
		show=$(( actual < max ? actual : max ))
		rumno -t "$timeout" -v "$show"
	fi
}

pashowvolume
